### ISSUE TITLE
Browser Inspect shows *.scss instead of *.css ?

### ISSUE THREAD

**Issue by comfytoday** [eddiemachado/bones#750]
I've been working on the a site made with Bones recently, and  I've just noticed that browsers are referencing the SCSS files [alongside the style rules] in the Inspector, rather than the .CSS files.

Even if I rename the .SCSS folder, or even delete it entirely from the server, it still tries to reference the .SCSS file. 

Is it able to reference the .SCSS file, even though it is actually pulling the style from .CSS? Like a reverse lookup? Or is something screwy with this site?

Here's the site if you're interested: http://www.wilopizza.com.au/

It's the same behaviour in both Firefox and Chrome.

**Comment by fraenk** [comment]
that's because you are having a sourcemap. I don't think it comes with bones but rather has been created in your scss setup.

see here to learn what this is: http://www.sitepoint.com/using-source-maps-debug-sass-chrome/ 

you'll have to turn that off in your scss configuration if you don't want to show that in your production environment

**Comment by comfytoday** [comment]
Great, that's exactly what it is. Compiling with Grunt. Thank you.
